import localFont from "next/font/local";
import "./globals.css";
import logo from "../assets/loansaathi.png";

import { ThemeProvider } from "@/components/theme-provider";
import {
    ClerkProvider,
    SignInButton,
    SignedIn,
    SignedOut,
    UserButton,
} from "@clerk/nextjs";
import { LanguageProvider } from "@/lib/languageContext";
import FloatingAssistant from "@/components/FloatingAssistant";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata = {
    title: "Loanसाथी",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <ClerkProvider
            appearance={{
                layout: {
                    logoImageUrl: logo,
                    socialButtonsVariant: "iconButton",
                    unsafe_disableDevelopmentModeWarnings: true,
                },
            }}
        >
            <html lang="en" suppressHydrationWarning>
                <head>
                    <meta charSet="utf-8" />
                    <title>Loanसाथी</title>
                    <meta name="description" content="LoanSaathi" />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1"
                    />
                    <link rel="icon" href="/icons/loansaathi-inverted.png" />
                    <link
                        rel="apple-touch-icon"
                        href="/icons/loansaathi-inverted.png"
                    />
                </head>
                <body
                    className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                >
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <LanguageProvider>
                            {children}
                            <FloatingAssistant />
                        </LanguageProvider>
                    </ThemeProvider>
                </body>
            </html>
        </ClerkProvider>
    );
}
